import { Link, useParams } from "react-router-dom";
import { ArrowRight, Check } from "lucide-react";
import { SiteNavbar } from "@/components/SiteNavbar";
import { SiteFooter } from "@/components/SiteFooter";
import { ExpertCTA } from "@/components/ExpertCTA";
import { Seo } from "@/components/Seo";
import { useLang, type Bi } from "@/i18n/LanguageContext";

export type IntentPageData = {
  slug: string;
  eyebrow: Bi;
  title: Bi;
  accent: Bi;
  intro: Bi;
  question: Bi;
  answer: Bi;
  signals: Bi[];
  system: { title: Bi; body: Bi }[];
  limit: Bi;
  related: string[];
};

const data: IntentPageData[] = [
  { slug:"growth", eyebrow:{es:"Growth",en:"Growth"}, title:{es:"Growth no es hacer más cosas.",en:"Growth is not doing more things."}, accent:{es:"Es encontrar qué mueve el negocio.",en:"It is finding what moves the business."}, intro:{es:"Conectamos producto, oferta, adquisición, conversión, ventas y retención para encontrar el cuello de botella que realmente frena el crecimiento.",en:"We connect product, offer, acquisition, conversion, sales, and retention to find the bottleneck actually holding growth back."}, question:{es:"¿Por qué hay actividad pero no crecimiento?",en:"Why is there activity but no growth?"}, answer:{es:"Porque canales y equipos suelen optimizar métricas separadas. Growth empieza con una meta de negocio, una hipótesis y una forma de comprobarla.",en:"Because channels and teams often optimize separate metrics. Growth starts with a business goal, a hypothesis, and a way to test it."}, signals:[{es:"Muchos reportes, pocas decisiones",en:"Many reports, few decisions"},{es:"Cada canal cuenta una historia distinta",en:"Each channel tells a different story"},{es:"No hay una prioridad compartida",en:"There is no shared priority"}], system:[{title:{es:"Diagnosticar",en:"Diagnose"},body:{es:"Economía, oferta, datos y fricciones.",en:"Economics, offer, data, and friction."}},{title:{es:"Priorizar",en:"Prioritize"},body:{es:"Una apuesta medible a la vez.",en:"One measurable bet at a time."}},{title:{es:"Escalar",en:"Scale"},body:{es:"Repetir lo que crea valor real.",en:"Repeat what creates real value."}}],limit:{es:"No prometemos crecimiento sin acceso a datos, capacidad operativa ni una oferta que el mercado quiera.",en:"We do not promise growth without data access, operating capacity, or an offer the market wants."},related:["performance-marketing","generacion-de-leads","crm"] },
  { slug:"performance-marketing", eyebrow:{es:"Performance marketing",en:"Performance marketing"}, title:{es:"La pauta compra atención.",en:"Paid media buys attention."}, accent:{es:"No arregla el negocio.",en:"It does not fix the business."}, intro:{es:"Diseñamos adquisición pagada alrededor de margen, conversión y capacidad comercial, no alrededor de clicks baratos.",en:"We design paid acquisition around margin, conversion, and sales capacity—not cheap clicks."}, question:{es:"¿Cuándo conviene invertir más?",en:"When should you invest more?"}, answer:{es:"Cuando la oferta convierte, el seguimiento funciona y conoces cuánto puedes pagar por un cliente. Entonces la pauta acelera una máquina probada.",en:"When the offer converts, follow-up works, and you know what you can pay for a customer. Then media accelerates a proven machine."}, signals:[{es:"Leads baratos que nunca compran",en:"Cheap leads that never buy"},{es:"Ventas sin atribución confiable",en:"Sales without reliable attribution"},{es:"Presupuesto sube y el margen baja",en:"Budget rises while margin falls"}], system:[{title:{es:"Economía",en:"Economics"},body:{es:"CAC, margen y payback antes del presupuesto.",en:"CAC, margin, and payback before budget."}},{title:{es:"Creatividad",en:"Creative"},body:{es:"Mensajes y formatos que prueban hipótesis.",en:"Messages and formats that test hypotheses."}},{title:{es:"Lectura",en:"Review"},body:{es:"Decisiones semanales conectadas a ventas.",en:"Weekly decisions tied to sales."}}],limit:{es:"No usamos pauta como respirador artificial para una oferta que no convierte.",en:"We do not use paid media as life support for an offer that does not convert."},related:["growth","generacion-de-leads","ecommerce-growth"] },
  { slug:"automatizacion-de-marketing", eyebrow:{es:"Automatización",en:"Automation"}, title:{es:"Automatiza la repetición.",en:"Automate repetition."}, accent:{es:"No el criterio.",en:"Not judgment."}, intro:{es:"Conectamos respuestas, seguimiento, citas, cotizaciones, reseñas y reactivación para que las oportunidades no dependan de la memoria.",en:"We connect replies, follow-up, appointments, quotes, reviews, and reactivation so opportunities do not depend on memory."}, question:{es:"¿Qué vale la pena automatizar?",en:"What is worth automating?"}, answer:{es:"Lo frecuente, predecible y medible. Las conversaciones complejas y las decisiones sensibles siguen necesitando personas.",en:"What is frequent, predictable, and measurable. Complex conversations and sensitive decisions still need people."}, signals:[{es:"Los leads esperan horas",en:"Leads wait for hours"},{es:"Nadie sabe quién debe seguir",en:"Nobody knows who follows up"},{es:"Clientes olvidados después de comprar",en:"Customers forgotten after buying"}], system:[{title:{es:"Mapear",en:"Map"},body:{es:"Definir eventos, dueños y excepciones.",en:"Define events, owners, and exceptions."}},{title:{es:"Conectar",en:"Connect"},body:{es:"CRM, WhatsApp, correo y calendario.",en:"CRM, WhatsApp, email, and calendar."}},{title:{es:"Escalar a humano",en:"Human handoff"},body:{es:"La automatización sabe cuándo detenerse.",en:"Automation knows when to stop."}}],limit:{es:"No fingimos que una IA puede manejar una venta compleja de principio a fin.",en:"We do not pretend AI can handle a complex sale end to end."},related:["crm","generacion-de-leads","growth-para-b2b"] },
  { slug:"crm", eyebrow:{es:"CRM",en:"CRM"}, title:{es:"Un CRM vacío no vende.",en:"An empty CRM does not sell."}, accent:{es:"Un proceso claro sí ayuda.",en:"A clear process does."}, intro:{es:"Diseñamos la operación comercial alrededor de etapas reales, tiempos de respuesta y siguientes acciones visibles.",en:"We design sales operations around real stages, response times, and visible next actions."}, question:{es:"¿Por qué el equipo no usa el CRM?",en:"Why does the team not use the CRM?"}, answer:{es:"Suele pedir demasiado y devolver muy poco. El sistema debe reducir trabajo, mostrar prioridades y ayudar a cerrar, no convertirse en otra obligación administrativa.",en:"It often asks for too much and gives too little back. The system should reduce work, show priorities, and help close—not become another administrative chore."}, signals:[{es:"Prospectos en hojas distintas",en:"Prospects in separate sheets"},{es:"Seguimientos sin fecha",en:"Follow-ups without dates"},{es:"Pipeline que nadie cree",en:"A pipeline nobody trusts"}], system:[{title:{es:"Etapas",en:"Stages"},body:{es:"Estados comerciales que el equipo reconoce.",en:"Sales states the team recognizes."}},{title:{es:"Acciones",en:"Actions"},body:{es:"Cada oportunidad tiene un siguiente paso.",en:"Every opportunity has a next step."}},{title:{es:"Visibilidad",en:"Visibility"},body:{es:"Pronóstico basado en actividad real.",en:"Forecast based on real activity."}}],limit:{es:"La herramienta no corrige por sí sola una oferta débil ni un equipo sin disciplina comercial.",en:"The tool alone cannot fix a weak offer or a team without sales discipline."},related:["automatizacion-de-marketing","growth-para-b2b","generacion-de-leads"] },
  { slug:"seo-aeo", eyebrow:{es:"SEO + AEO",en:"SEO + AEO"}, title:{es:"Responde mejor.",en:"Answer better."}, accent:{es:"No publiques más por publicar.",en:"Do not publish for volume."}, intro:{es:"Construimos autoridad alrededor de preguntas reales, experiencia demostrable y páginas que ayudan tanto a personas como a buscadores y asistentes de IA.",en:"We build authority around real questions, demonstrated experience, and pages that help people, search engines, and AI assistants."}, question:{es:"¿AEO reemplaza al SEO?",en:"Does AEO replace SEO?"}, answer:{es:"No. Una base técnica sana, contenido útil y evidencia siguen siendo el fundamento. La claridad de las respuestas ayuda a que distintos sistemas entiendan y citen tu trabajo.",en:"No. A sound technical base, useful content, and evidence remain the foundation. Clear answers help different systems understand and cite your work."}, signals:[{es:"Contenido genérico sin experiencia",en:"Generic content without experience"},{es:"Páginas que compiten entre sí",en:"Pages competing with each other"},{es:"Tráfico que no entiende la oferta",en:"Traffic that does not understand the offer"}], system:[{title:{es:"Intención",en:"Intent"},body:{es:"Una pregunta concreta por página.",en:"One concrete question per page."}},{title:{es:"Evidencia",en:"Evidence"},body:{es:"Experiencia, casos y fuentes confiables.",en:"Experience, cases, and reliable sources."}},{title:{es:"Distribución",en:"Distribution"},body:{es:"Enlaces, formatos y actualización útil.",en:"Links, formats, and useful updates."}}],limit:{es:"No prometemos posiciones ni fabricamos granjas de contenido con IA.",en:"We do not promise rankings or manufacture AI content farms."},related:["growth","generacion-de-leads","marketing-para-pymes"] },
  { slug:"ecommerce-growth", eyebrow:{es:"E-commerce growth",en:"E-commerce growth"}, title:{es:"Más tráfico no siempre significa",en:"More traffic does not always mean"}, accent:{es:"más ventas.",en:"more sales."}, intro:{es:"Conectamos adquisición, experiencia de compra, oferta, margen, recompra y cohortes para crecer sin esconder fugas detrás de la pauta.",en:"We connect acquisition, shopping experience, offer, margin, repeat purchase, and cohorts to grow without hiding leaks behind media spend."}, question:{es:"¿Dónde se pierde el crecimiento de una tienda?",en:"Where does an online store lose growth?"}, answer:{es:"Puede estar antes del click, en la página, en el checkout o después de la primera compra. Se diagnostica por etapa y cohorte, no con una métrica aislada.",en:"It can happen before the click, on the page, at checkout, or after the first purchase. Diagnose by stage and cohort, not one isolated metric."}, signals:[{es:"Conversión cae al subir tráfico",en:"Conversion drops as traffic rises"},{es:"Dependencia de descuentos",en:"Dependence on discounts"},{es:"La segunda compra nunca llega",en:"The second purchase never comes"}], system:[{title:{es:"Adquirir",en:"Acquire"},body:{es:"Audiencias, creatividad y costo sostenible.",en:"Audiences, creative, and sustainable cost."}},{title:{es:"Convertir",en:"Convert"},body:{es:"Oferta, experiencia, checkout y confianza.",en:"Offer, experience, checkout, and trust."}},{title:{es:"Retener",en:"Retain"},body:{es:"RFM, recompra, lealtad y referidos.",en:"RFM, repeat purchase, loyalty, and referrals."}}],limit:{es:"No escalamos inversión si la unidad económica se rompe con cada nueva venta.",en:"We do not scale spend if unit economics break with every new sale."},related:["growth-para-ecommerce","performance-marketing","seo-aeo"] },
  { slug:"generacion-de-leads", eyebrow:{es:"Generación de leads",en:"Lead generation"}, title:{es:"Un lead no es una venta.",en:"A lead is not a sale."}, accent:{es:"Es el inicio del trabajo.",en:"It is the start of the work."}, intro:{es:"Diseñamos demanda, captura, calificación y seguimiento como un solo recorrido, con una definición compartida de qué es una oportunidad útil.",en:"We design demand, capture, qualification, and follow-up as one journey, with a shared definition of a useful opportunity."}, question:{es:"¿Por qué los leads no convierten?",en:"Why do leads not convert?"}, answer:{es:"A veces son malos; muchas veces llegan a una oferta confusa, reciben respuesta tarde o entran a un proceso comercial que no distingue intención.",en:"Sometimes they are poor; often they meet an unclear offer, a late response, or a sales process that does not distinguish intent."}, signals:[{es:"Volumen sin calidad",en:"Volume without quality"},{es:"Respuesta demasiado lenta",en:"Response is too slow"},{es:"Marketing y ventas se culpan",en:"Marketing and sales blame each other"}], system:[{title:{es:"Demanda",en:"Demand"},body:{es:"Mensaje y canal según la intención.",en:"Message and channel by intent."}},{title:{es:"Captura",en:"Capture"},body:{es:"Formularios y páginas sin fricción inútil.",en:"Forms and pages without needless friction."}},{title:{es:"Seguimiento",en:"Follow-up"},body:{es:"Velocidad, cadencia y calificación.",en:"Speed, cadence, and qualification."}}],limit:{es:"No vendemos bases ni prometemos leads que el equipo no puede atender.",en:"We do not sell lists or promise leads the team cannot handle."},related:["crm","performance-marketing","growth-para-b2b"] },
  { slug:"growth-para-b2b", eyebrow:{es:"Growth para B2B",en:"B2B growth"}, title:{es:"B2B crece con confianza,",en:"B2B grows through trust,"}, accent:{es:"proceso y seguimiento.",en:"process, and follow-up."}, intro:{es:"Alineamos autoridad, generación de demanda, prospección, pipeline y habilitación comercial para ciclos de venta largos y decisiones con varias personas.",en:"We align authority, demand generation, prospecting, pipeline, and sales enablement for long cycles and multi-person decisions."}, question:{es:"¿Cómo se acelera una venta compleja?",en:"How do you accelerate a complex sale?"}, answer:{es:"No presionando más, sino reduciendo incertidumbre: mejor información, señales de confianza, responsables claros y siguientes pasos concretos.",en:"Not by pushing harder, but by reducing uncertainty: better information, trust signals, clear owners, and concrete next steps."}, signals:[{es:"Pipeline lleno pero inmóvil",en:"Full but motionless pipeline"},{es:"Dependencia total de referidos",en:"Total dependence on referrals"},{es:"Propuestas sin seguimiento",en:"Proposals without follow-up"}], system:[{title:{es:"Autoridad",en:"Authority"},body:{es:"Contenido y evidencia para decisiones serias.",en:"Content and evidence for serious decisions."}},{title:{es:"Demanda",en:"Demand"},body:{es:"Inbound, outbound, alianzas y eventos.",en:"Inbound, outbound, partnerships, and events."}},{title:{es:"Pipeline",en:"Pipeline"},body:{es:"Calificación, velocidad y avance visible.",en:"Qualification, speed, and visible progress."}}],limit:{es:"No confundimos una lista de contactos con una estrategia de demanda B2B.",en:"We do not confuse a contact list with a B2B demand strategy."},related:["crm","generacion-de-leads","automatizacion-de-marketing"] },
  { slug:"growth-para-ecommerce", eyebrow:{es:"Growth para e-commerce",en:"Growth for e-commerce"}, title:{es:"Adquirir, convertir y retener.",en:"Acquire, convert, and retain."}, accent:{es:"En ese orden y juntos.",en:"In that order, together."}, intro:{es:"Trabajamos la tienda como una economía completa: contribución por pedido, conversión, frecuencia, mezcla de canales y valor del cliente.",en:"We work on the store as a complete economy: contribution per order, conversion, frequency, channel mix, and customer value."}, question:{es:"¿Qué métrica manda?",en:"Which metric matters most?"}, answer:{es:"Depende del cuello de botella. CAC sin margen engaña; conversión sin calidad de tráfico engaña; ROAS sin recompra cuenta una historia incompleta.",en:"It depends on the bottleneck. CAC without margin misleads; conversion without traffic quality misleads; ROAS without repeat purchase tells an incomplete story."}, signals:[{es:"ROAS alto pero caja apretada",en:"High ROAS but tight cash"},{es:"Clientes de una sola compra",en:"One-purchase customers"},{es:"Campañas que compiten entre sí",en:"Campaigns competing with each other"}], system:[{title:{es:"Unidad económica",en:"Unit economics"},body:{es:"Margen, CAC, LTV y tiempo de retorno.",en:"Margin, CAC, LTV, and payback."}},{title:{es:"Experiencia",en:"Experience"},body:{es:"Merchandising, oferta, CRO y checkout.",en:"Merchandising, offer, CRO, and checkout."}},{title:{es:"Cohortes",en:"Cohorts"},body:{es:"Retención real por origen y producto.",en:"Real retention by source and product."}}],limit:{es:"No optimizamos ROAS aislado si el crecimiento empeora margen, inventario o flujo de caja.",en:"We do not optimize isolated ROAS if growth worsens margin, inventory, or cash flow."},related:["ecommerce-growth","performance-marketing","seo-aeo"] },
  { slug:"marketing-para-pymes", eyebrow:{es:"Marketing para pymes",en:"Marketing for small businesses"}, title:{es:"No necesitas hacer todo.",en:"You do not need to do everything."}, accent:{es:"Necesitas saber qué va primero.",en:"You need to know what comes first."}, intro:{es:"Ayudamos a negocios pequeños y medianos a ordenar oferta, presencia, adquisición y seguimiento sin contratar cinco proveedores desconectados.",en:"We help small and mid-sized businesses organize offer, presence, acquisition, and follow-up without hiring five disconnected vendors."}, question:{es:"¿Cuál es el primer paso?",en:"What is the first step?"}, answer:{es:"Entender cómo entra dinero hoy y dónde se pierde. A partir de ahí elegimos una prioridad que el equipo y el presupuesto sí puedan sostener.",en:"Understand how money comes in today and where it leaks. From there, choose one priority the team and budget can sustain."}, signals:[{es:"El dueño coordina a todos",en:"The owner coordinates everyone"},{es:"Cada mes cambia la prioridad",en:"Priorities change every month"},{es:"No hay seguimiento comercial",en:"There is no sales follow-up"}], system:[{title:{es:"Orden",en:"Order"},body:{es:"Oferta, números y una prioridad.",en:"Offer, numbers, and one priority."}},{title:{es:"Base",en:"Foundation"},body:{es:"Sitio, medición, captura y seguimiento.",en:"Site, measurement, capture, and follow-up."}},{title:{es:"Volumen",en:"Volume"},body:{es:"Contenido, referidos y pauta cuando toca.",en:"Content, referrals, and ads when ready."}}],limit:{es:"No recomendamos una infraestructura que el negocio todavía no puede operar.",en:"We do not recommend infrastructure the business cannot operate yet."},related:["growth","crm","seo-aeo"] },
];

const findIntent = (slug?: string) => data.find((item) => item.slug === slug);

export default function IntentPage() {
  const { slug } = useParams();
  const page = findIntent(slug);
  const { t, pick } = useLang();
  if (!page) return null;
  return <div className="min-h-screen bg-[hsl(var(--paper))] font-body"><Seo title={{es:`${page.eyebrow.es} | Estudio Oasis`,en:`${page.eyebrow.en} | Estudio Oasis`}} description={page.intro} path={`/${page.slug}`} /><div className="grain-overlay" aria-hidden /><SiteNavbar />
    <main className="pt-32 md:pt-36">
      <section className="pb-16 md:pb-24"><div className="mx-auto max-w-[1700px] px-4 md:px-6"><p className="font-label text-[hsl(var(--ink)/.42)]">{pick(page.eyebrow)}</p><h1 className="mt-5 max-w-[16ch] font-ultra text-[clamp(42px,9vw,150px)] leading-[.89] text-[hsl(var(--ink))]">{pick(page.title)} <span className="text-destructive">{pick(page.accent)}</span></h1><p className="mt-7 max-w-[68ch] text-[16px] leading-relaxed text-[hsl(var(--ink)/.62)] md:text-[19px]">{pick(page.intro)}</p><div className="mt-8"><ExpertCTA source={page.slug} /></div></div></section>
      <section className="border-t-2 border-[hsl(var(--ink))] py-14 md:py-20"><div className="mx-auto grid max-w-[1700px] gap-10 px-4 md:px-6 lg:grid-cols-[1fr_1fr]"><h2 className="font-ultra text-[clamp(34px,6vw,88px)] leading-[.94] text-[hsl(var(--ink))]">{pick(page.question)}</h2><p className="font-condensed text-[clamp(22px,3vw,38px)] leading-[1.1] text-[hsl(var(--ink)/.62)]">{pick(page.answer)}</p></div></section>
      <section className="bg-[hsl(var(--ink))] py-14 md:py-20"><div className="mx-auto max-w-[1700px] px-4 md:px-6"><p className="font-label text-[hsl(var(--paper)/.42)]">{t("Señales del problema", "Signals of the problem")}</p><div className="mt-6 grid md:grid-cols-3">{page.signals.map((signal)=><div key={signal.es} className="border-t border-[hsl(var(--paper)/.2)] py-6 md:border-r md:px-6 md:first:pl-0"><Check className="h-5 w-5 text-destructive"/><p className="mt-4 font-condensed text-[clamp(21px,3vw,32px)] leading-none text-[hsl(var(--paper))]">{pick(signal)}</p></div>)}</div></div></section>
      <section className="py-14 md:py-20"><div className="mx-auto max-w-[1700px] px-4 md:px-6"><p className="font-label text-[hsl(var(--ink)/.42)]">{t("El sistema recomendado", "The recommended system")}</p><div className="mt-6 grid border-t-2 border-[hsl(var(--ink))] md:grid-cols-3">{page.system.map((item,i)=><div key={item.title.es} className="border-b border-[hsl(var(--ink)/.15)] py-6 md:border-b-0 md:border-r md:px-6 md:first:pl-0"><span className="font-ultra text-[40px] text-destructive">0{i+1}</span><h2 className="mt-2 font-condensed text-[clamp(22px,3vw,34px)] leading-none text-[hsl(var(--ink))]">{pick(item.title)}</h2><p className="mt-3 text-[15px] leading-relaxed text-[hsl(var(--ink)/.58)]">{pick(item.body)}</p></div>)}</div><div className="mt-10 border-l-4 border-destructive pl-5"><p className="font-label text-destructive">{t("Límite honesto", "Honest limit")}</p><p className="mt-2 max-w-[68ch] text-[16px] leading-relaxed text-[hsl(var(--ink)/.65)]">{pick(page.limit)}</p></div></div></section>
      <section className="border-t-2 border-[hsl(var(--ink))] py-14"><div className="mx-auto max-w-[1700px] px-4 md:px-6"><p className="font-label text-[hsl(var(--ink)/.42)]">{t("También puede ayudarte", "Related")}</p><div className="mt-5 flex flex-wrap gap-3">{page.related.map((related)=>{const item=findIntent(related);return item?<Link key={related} to={`/${related}`} className="inline-flex min-h-11 items-center gap-2 border-2 border-[hsl(var(--ink)/.2)] px-4 font-label text-[hsl(var(--ink))] hover:border-[hsl(var(--ink))]">{pick(item.eyebrow)} <ArrowRight className="h-4 w-4"/></Link>:null})}<Link to="/recursos/colectivo-anti-vendehumo" className="inline-flex min-h-11 items-center gap-2 border-2 border-[hsl(var(--ink)/.2)] px-4 font-label text-[hsl(var(--ink))]">Colectivo Anti-Vendehumo <ArrowRight className="h-4 w-4"/></Link></div></div></section>
    </main><SiteFooter /></div>;
}
