import { ArrowRight, BookOpen } from "lucide-react";
import { Link } from "react-router-dom";
import { SiteNavbar } from "@/components/SiteNavbar";
import { SiteFooter } from "@/components/SiteFooter";
import { useLang } from "@/i18n/LanguageContext";
import { useScrollReveal, useSmoothScroll } from "@/hooks/useSmoothScroll";

export default function RecursosPage() {
  const { t } = useLang();
  useSmoothScroll(); useScrollReveal();
  return <div className="min-h-screen bg-[hsl(var(--paper))] font-body"><div className="grain-overlay" aria-hidden/><SiteNavbar/><main className="pt-24 md:pt-28"><section className="max-w-[1700px] mx-auto px-4 md:px-6 pb-14 md:pb-24"><p className="font-label text-[hsl(var(--ink)/0.4)]">{t("Recursos", "Resources")}</p><h1 className="mt-5 max-w-[13ch] font-ultra text-[clamp(48px,11vw,180px)] md:text-[min(9vw,15vh)] leading-[0.88] text-[hsl(var(--ink))]">{t("Criterio para tomar mejores decisiones.", "Judgment for better decisions.")}</h1><p className="mt-7 max-w-[60ch] text-[15px] md:text-[18px] leading-relaxed text-[hsl(var(--ink)/0.55)]">{t("Guías, herramientas y conversaciones para entender crecimiento sin depender de promesas, jerga o dashboards bonitos.", "Guides, tools, and conversations for understanding growth without relying on promises, jargon, or pretty dashboards.")}</p></section><section className="border-t-2 border-[hsl(var(--ink))]" data-reveal><Link to="/recursos/colectivo-anti-vendehumo" className="group block max-w-[1700px] mx-auto px-4 md:px-6 py-12 md:py-20"><div className="grid md:grid-cols-[0.7fr_1.3fr_auto] gap-7 md:gap-12 items-start"><div><BookOpen className="h-8 w-8 text-[#C5221F]"/><p className="mt-5 font-label text-[hsl(var(--ink)/0.4)]">{t("Manifiesto + herramientas", "Manifesto + tools")}</p></div><div><h2 className="font-ultra text-[clamp(38px,7vw,110px)] leading-[0.9] text-[hsl(var(--ink))]">{t("Colectivo Anti‑Vendehumo", "Anti‑Smoke Collective")}</h2><p className="mt-5 max-w-[60ch] text-[15px] md:text-[18px] leading-relaxed text-[hsl(var(--ink)/0.58)]">{t("Marketing para la gente que paga la nómina. Un manifiesto para distinguir herramientas de estrategia, métricas de resultados y explicaciones de excusas.", "Marketing for the people who make payroll. A manifesto for distinguishing tools from strategy, metrics from outcomes, and explanations from excuses.")}</p><div className="mt-6 flex flex-wrap gap-2">{[t("Detector de humo","Smoke detector"),"Growth economics",t("Plantilla de hipótesis","Hypothesis template"),"Playbook"].map(x=><span key={x} className="border border-[hsl(var(--ink)/0.2)] px-3 py-2 font-label text-[hsl(var(--ink)/0.55)]">{x}</span>)}</div></div><span className="h-12 w-12 border-2 border-[hsl(var(--ink))] flex items-center justify-center group-hover:bg-[#C5221F] group-hover:text-[hsl(var(--paper))] group-hover:border-[#C5221F] transition-colors"><ArrowRight className="h-5 w-5"/></span></div></Link></section></main><SiteFooter/></div>;
}
